import json
import os
import shutil
def save_to_json(data, output_file_path):
    with open(output_file_path, 'w') as output_file:
        json.dump(data, output_file, indent=2)


data_to_save = \
{
    "Project Location": {
        # -----------------------------------------------------------------------------------------------------------------------
        "Number":
            """09""",
        # -----------------------------------------------------------------------------------------------------------------------
        "Year":
            """2024""",
        # -----------------------------------------------------------------------------------------------------------------------
        "Semester":
            """Fall""",
    },


    "Project Information": {
        # -----------------------------------------------------------------------------------------------------------------------
        "WB_lead":
            """Holti Banka""",
        # -----------------------------------------------------------------------------------------------------------------------
        "unit_name":
            """Financial Inclusion, Infrastructure & Access (EFNFI)""",
        # -----------------------------------------------------------------------------------------------------------------------
        "project_name":
            """Accelerating Adoption of Fast Payments in Low and Middle Income Countries (P180236)""",
        # -----------------------------------------------------------------------------------------------------------------------
        "project_lead":
            """Yes""",
        # -----------------------------------------------------------------------------------------------------------------------
        "team_members":
            """Oya Ardic""",
    },


    "Challenge": {
        # -----------------------------------------------------------------------------------------------------------------------
        "challenge_location":
            """Global scope of domestic and cross-border corridors.""",
        # -----------------------------------------------------------------------------------------------------------------------
        "challenge_type":
            """We are establishing an innovative dataset/methodology that would collect, analyze and disseminate costs associated with domestic and cross-border payment
transactions across different payment methods, transaction channels and payment service providers around the world.""",
        # -----------------------------------------------------------------------------------------------------------------------
        "solution_beneficiaries":
            """
Central banks, governments, academia, policy/research institutes, think tanks, donor community, financial institutions, international development organizations.
            """,
    },


    "Status and Timeline": {
        # -----------------------------------------------------------------------------------------------------------------------
        "project_status":
            """The methodology and data analysis on the domestic payment costs is in early stages while the equivalent methodology on the cross-border payment costs is
advances but new ideas are being explored on data analysis and data visualization.
            """,
        # -----------------------------------------------------------------------------------------------------------------------
        "project_milestones":
            """
Reports based on new types of data analysis and data visualization are expected to be generated by the end of the project.
            """,
        # -----------------------------------------------------------------------------------------------------------------------
        "lead_meeting":
            """Yes""",
    },


    "Data": {
        # -----------------------------------------------------------------------------------------------------------------------
        "dataset_size":
            """About 15 MB""",
        # -----------------------------------------------------------------------------------------------------------------------
        "data_type":
            """
1. Time series/Panel data
            """,
        # -----------------------------------------------------------------------------------------------------------------------
        "data_details":
            """
A mix of quantitative and qualitative data, focusing on the costs borne by end users when sending/receiving a domestic or cross-border payment, by type of
provide (bank, non-bank), by payment method (cash, card, e-money, credit transfer), by speed, by transaction channel (branch, internet, mobile, etc).
            """,
        # -----------------------------------------------------------------------------------------------------------------------
        "STC_requirement":
            """They can have immediate access.""",
        # -----------------------------------------------------------------------------------------------------------------------
        "data_sample":
            """Yes""",
        # -----------------------------------------------------------------------------------------------------------------------
        "ultimate_goal":
            """Finding new insights, patterns from the data, as well as visualizing the data in a more meaningful way. The data has the essential information to accomplish this
goal.""",
        # -----------------------------------------------------------------------------------------------------------------------
        "additional_comments":
            """This particular dataset is one of the most cited World Bank datasets in the international development community.""",
    },


        # -----------------------------------------------------------------------------------------------------------------------
        "Proposed by": "World Bank",
        "Proposed by email": "firstname_lastname@worldbank.org",
        "instructor": "Amir Jafari & Edwin Lo",
        "instructor1_email": "ajafari@gmail.com",
        "instructor2_email": "edwinlo@gwu.edu",
        "github_repo": "https://github.com/amir-jafari/Capstone",
        # -----------------------------------------------------------------------------------------------------------------------
}

os.makedirs(os.getcwd() + os.sep + f'Arxiv{os.sep}Proposals{os.sep}{data_to_save["Project Location"]["Year"]}{os.sep}{data_to_save["Project Location"]["Semester"]}{os.sep}World Bank{os.sep}{data_to_save["Project Location"]["Number"]}',exist_ok=True)
output_file_path = os.getcwd() + os.sep + f'Arxiv\Proposals{os.sep}{data_to_save["Project Location"]["Year"]}{os.sep}{data_to_save["Project Location"]["Semester"]}{os.sep}World Bank{os.sep}{data_to_save["Project Location"]["Number"]}{os.sep}'
save_to_json(data_to_save, output_file_path + "input.json")
shutil.copy(os.path.abspath(os.path.join(os.path.dirname(__file__), 'json_gen.py')), output_file_path)
print(f"Data saved to {output_file_path}")